version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      #- npm install

  build:
    commands:
      - echo "Building the project..."
      #- npm run build

  post_build:
    commands:
      - echo "Running tests..."
      #- npm test
